# Generated by Django 6.0.6 on 2026-06-14 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['tenant__nombre', 'nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('prueba', 'Prueba'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='prueba', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
