# Generated by Django 6.0.6 on 2026-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_sucursal_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['nombre'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cuit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('prueba', 'Prueba'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='prueba', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
