# Generated by Django 6.0.6 on 2026-06-14 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_categoria_options_alter_producto_options_and_more'),
        ('tenants', '0002_alter_sucursal_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('recibida', 'Recibida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tenants.tenant', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_items', to='products.producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de orden',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(default='activo', max_length=30, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='purchases.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='unique_proveedor_nombre_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['tenant', 'proveedor', 'fecha'], name='purchases_c_tenant__6881f3_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['tenant', 'estado', 'fecha'], name='purchases_c_tenant__5c9e2c_idx'),
        ),
    ]
