# Generated by Django 6.0.6 on 2026-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraitem',
            options={'ordering': ['id'], 'verbose_name': 'Producto de la orden', 'verbose_name_plural': 'Productos de la orden'},
        ),
    ]
