# Generated by Django 6.0.6 on 2026-06-14 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_categoria_options_alter_producto_options_and_more'),
        ('tenants', '0002_alter_sucursal_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('desperdicio', 'Desperdicio'), ('vencimiento', 'Vencimiento'), ('devolucion', 'Devolucion')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_movimientos', to='products.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_movimientos', to='tenants.sucursal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_movimientos', to='tenants.tenant', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tenant', 'producto', 'fecha'], name='inventory_i_tenant__dbe3e3_idx'), models.Index(fields=['tenant', 'sucursal', 'fecha'], name='inventory_i_tenant__e4ad53_idx'), models.Index(fields=['tenant', 'tipo_movimiento', 'fecha'], name='inventory_i_tenant__ed5c50_idx')],
            },
        ),
    ]
