# Generated by Django 6.0.6 on 2026-06-14 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_sucursal_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caja_sessions', to='tenants.sucursal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_sessions', to='tenants.tenant', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caja_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura y cierre de caja',
                'verbose_name_plural': 'Aperturas y cierres de caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('ajuste', 'Ajuste')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_movimientos', to='tenants.tenant', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caja_movimientos', to=settings.AUTH_USER_MODEL)),
                ('caja_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cash.cajasession')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='cajasession',
            index=models.Index(fields=['tenant', 'sucursal', 'estado'], name='cash_cajase_tenant__43a0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasession',
            index=models.Index(fields=['tenant', 'fecha_apertura'], name='cash_cajase_tenant__04388b_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['tenant', 'caja_session', 'fecha'], name='cash_cajamo_tenant__83d13a_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['tenant', 'tipo', 'fecha'], name='cash_cajamo_tenant__0202fd_idx'),
        ),
    ]
