# Generated by Django 6.0.6 on 2026-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajasession',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Caja'},
        ),
    ]
