# Generated by Django 6.0.6 on 2026-06-13 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('punto_reposicion', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='unique_categoria_nombre_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='unique_producto_nombre_por_tenant'),
        ),
    ]
