# Generated by Django 6.0.6 on 2026-06-14 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0002_alter_sucursal_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(default='activo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reposicion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Avisar reposición cuando queden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock máximo recomendado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Reposición mínima'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tenants.tenant', verbose_name='Empresa'),
        ),
    ]
